### ISSUE TITLE
CloudFlare DDos protection http page

### ISSUE THREAD

**Issue by Spoki4** [luzzif/bittrex-api-client#4]
Hi, when I tried to use your library, I ran into a problem.
Example code:
```typescript
import {BittrexApiClient} from "bittrex-api-client"

const bittrex = new BittrexApiClient('XXXXXXXXXXXXXXXXX', 'XXXXXXXXXXXXXXX');
bittrex.getBalances()
    .then((data) => {
        console.log(data)
    })
    .catch(err => console.log(err));
```
I got a html code of cloudflare page:
```
Error: Bittrex returned "<!DOCTYPE HTML>\n<html lang=\"en-US\">\n<head>\n  <meta charset=\"UTF-8\" />\n  <meta
http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n  <meta http-equiv=\"X-UA-Compatible\" con
tent=\"IE=Edge,chrome=1\" />\n  <meta name=\"robots\" content=\"noindex, nofollow\" />\n  <meta name=\"viewport
\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\n  <title>Just a moment...</title>\n  <s
tyle type=\"text/css\">\n    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}\n    body {backgrou
nd-color: #ffffff; font-family: Helvetica, Arial, sans-serif; font-size: 100%;}\n    h1 {font-size: 1.5em; colo
r: #404040; text-align: center;}\n    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0
;}\n    #spinner {margin: 0 auto 30px auto; display: block;}\n    .attribution {margin-top: 20px;}\n    @-webki
t-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translateY(10px); } 66% { -webkit-
transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transform: translateY(0); transfor
m: translateY(0); } }\n    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform: translat
eY(10px); } 66% { -webkit-transform: translateY(-10px); transform: translateY(-10px); } 100% { -webkit-transfor
m: translateY(0); transform: translateY(0); } }\n    .bubbles { background-color: #404040; width:15px; height:
15px; margin:2px; border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; animation:bubb
les 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:both; animation-fill-mode:both; display:inline
-block; }\n  </style>\n\n    <script type=\"text/javascript\">\n  //<![CDATA[\n  (function(){\n    var a = func
tion() {try{return !!window.addEventListener} catch(e) {return !1} },\n    b = function(b, c) {a() ? document.a
ddEventListener(\"DOMContentLoaded\", b, c) : document.attachEvent(\"onreadystatechange\", b)};\n    b(function
(){\n      var a = document.getElementById('cf-content');a.style.display = 'block';\n      setTimeout(function(
){\n        var s,t,o,p,b,r,e,a,k,i,n,g,f, VGkCrbU={\"FPRAGy\":+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+
!![]+!![]+!![]+!![]))};\n        t = document.createElement('div');\n        t.innerHTML=\"<a href='/'>x</a>\";
\n        t = t.firstChild.href;r = t.match(/https?:\\/\\//)[0];\n        t = t.substr(r.length); t = t.substr(
0,t.length-1);\n        a = document.getElementById('jschl-answer');\n        f = document.getElementById('chal
lenge-form');\n        ;VGkCrbU.FPRAGy-=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]));VGkCrbU.FPRAGy*=+((!+
[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = parseInt(VGkCrbU.FPRAGy, 10) + t.length; '; 12
1'\n        f.action += location.hash;\n        f.submit();\n      }, 4000);\n    }, false);\n  })();\n  //]]>\
n</script>\n\n\n</head>\n<body>\n  <table width=\"100%\" height=\"100%\" cellpadding=\"20\">\n    <tr>\n      <
td align=\"center\" valign=\"middle\">\n          <div class=\"cf-browser-verification cf-im-under-attack\">\n
 <noscript><h1 data-translate=\"turn_on_js\" style=\"color:#bd2426;\">Please turn JavaScript on and reload the
page.</h1></noscript>\n  <div id=\"cf-content\" style=\"display:none\">\n    \n    <div>\n      <div class=\"bu
bbles\"></div>\n      <div class=\"bubbles\"></div>\n      <div class=\"bubbles\"></div>\n    </div>\n    <h1><
span data-translate=\"checking_browser\">Checking your browser before accessing</span> bittrex.com.</h1>\n    \
n    <p data-translate=\"process_is_automatic\">This process is automatic. Your browser will redirect to your r
equested content shortly.</p>\n    <p data-translate=\"allow_5_secs\">Please allow up to 5 seconds&hellip;</p>\
n  </div>\n   \n  <form id=\"challenge-form\" action=\"/cdn-cgi/l/chk_jschl\" method=\"get\">\n    <input type=
\"hidden\" name=\"jschl_vc\" value=\"c5df085da23cefea6192438c9e980358\"/>\n    <input type=\"hidden\" name=\"pa
ss\" value=\"1513880569.672-7A31fc+khu\"/>\n    <input type=\"hidden\" id=\"jschl-answer\" name=\"jschl_answer\
"/>\n  </form>\n</div>\n\n          \n          <div class=\"attribution\">\n            <a href=\"https://www.
cloudflare.com/5xx-error-landing?utm_source=iuam\" target=\"_blank\" style=\"font-size: 12px;\">DDoS protection
 by Cloudflare</a>\n            <br>\n            Ray ID: 3d0cde5f7c894e1e\n          </div>\n      </td>\n
 \n    </tr>\n  </table>\n</body>\n</html>\n"
    at BittrexApiClient.<anonymous> (R:\test\node_modules\bittrex-api-client\build\BittrexApiCli
ent.js:406:19)
    at Generator.next (<anonymous>)
    at fulfilled (R:\test\node_modules\bittrex-api-client\build\BittrexApiClient.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```
But when I tried to use node-fetch for http request this works fine.
```typescript
import * as CryptoJs from "crypto-js";
import fetch from "node-fetch";

const url = `https://www.bittrex.com/api/v1.1/account/getbalances?apikey=XXXXXXXXXXXXXXXXXX&nonce=${new Date().getTime().toString()}`;
fetch(url, {
  headers: {
    apisign: CryptoJs.HmacSHA512(url, "XXXXXXXXXXXXXXXXXXXXXX").toString()
  }
})
  .then(data => data.json())
  .then(data => console.log(data))
  .catch(err => console.error(err));
```

**Comment by luzzif** [comment]
You closed the issue yourself I see. If the problem is solved can you tell the community what did you do in order to solve it? Thanks!

**Comment by Spoki4** [comment]
Solution was not found
